version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SendSMSStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3jzxv3ooeao9"
s3_prefix = "SendSMSStack"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

